development:
  host: localhost
  database: social_stock_ticker_development

test:
  host: localhost
  database: social_stock_ticker_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>


allow_dynamic_fields: false
