development:
  host: localhost
  database: social_stock_ticker_development

test:
  host: localhost
  database: social_stock_ticker_test

# set these environment variables on your prod server
production:
  host: localhost
  database: social_stock_ticker_production


allow_dynamic_fields: false
